<?xml version="1.0" encoding="utf-8"?><Database Name="QLNganHang" Class="QLNganHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=QLNganHang;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLNganHangConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietGD" Member="ChiTietGDs">
    <Type Name="ChiTietGD">
      <Column Name="MaGD" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoTKNguoiChuyen" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SoTKNguoiNhan" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="NgayGio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DienGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="TaiKhoan_ChiTietGD" Member="TaiKhoan" ThisKey="SoTKNguoiChuyen" OtherKey="IdTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamGiaTK" Member="ThamGiaTKs">
    <Type Name="ThamGiaTK">
      <Column Name="IdTaiKhoan" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="KhachHang_ThamGiaTK" Member="KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="TaiKhoan_ThamGiaTK" Member="TaiKhoan" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoDich" Member="GiaoDiches">
    <Type Name="GiaoDich">
      <Column Name="IdGiaoDich" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdTaiKhoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdLoaiGD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoGiaoDich" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoDu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LoaiGiaoDich_GiaoDich" Member="LoaiGiaoDich" ThisKey="IdLoaiGD" OtherKey="IdLoaiGD" Type="LoaiGiaoDich" IsForeignKey="true" />
      <Association Name="TaiKhoan_GiaoDich" Member="TaiKhoan" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Avarta" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiGiayTo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoGiayTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiCap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NganhChinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdNganh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NhanVienLV" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdLoaiKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_ThamGiaTK" Member="ThamGiaTKs" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="ThamGiaTK" />
      <Association Name="KhachHang_TaiKhoan" Member="TaiKhoans" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="TaiKhoan" />
      <Association Name="LoaiKhachHang_KhachHang" Member="LoaiKhachHang" ThisKey="IdLoaiKH" OtherKey="IdLoaiKH" Type="LoaiKhachHang" IsForeignKey="true" />
      <Association Name="Nganh_KhachHang" Member="Nganh" ThisKey="IdNganh" OtherKey="IdNganh" Type="Nganh" IsForeignKey="true" />
      <Association Name="NganhChinh_KhachHang" Member="NganhChinh1" ThisKey="NganhChinh" OtherKey="IdNganhChinh" Type="NganhChinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiGiaoDich" Member="LoaiGiaoDiches">
    <Type Name="LoaiGiaoDich">
      <Column Name="IdLoaiGD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiGD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LoaiGiaoDich_GiaoDich" Member="GiaoDiches" ThisKey="IdLoaiGD" OtherKey="IdLoaiGD" Type="GiaoDich" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiKhachHang" Member="LoaiKhachHangs">
    <Type Name="LoaiKhachHang">
      <Column Name="IdLoaiKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LoaiKhachHang_KhachHang" Member="KhachHangs" ThisKey="IdLoaiKH" OtherKey="IdLoaiKH" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiKhoan" Member="LoaiTaiKhoans">
    <Type Name="LoaiTaiKhoan">
      <Column Name="IdLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="TaiKhoans" ThisKey="IdLoai" OtherKey="IdLoai" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.Nganh" Member="Nganhs">
    <Type Name="Nganh">
      <Column Name="IdNganh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdNganhChinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Nganh_KhachHang" Member="KhachHangs" ThisKey="IdNganh" OtherKey="IdNganh" Type="KhachHang" />
      <Association Name="NganhChinh_Nganh" Member="NganhChinh" ThisKey="IdNganhChinh" OtherKey="IdNganhChinh" Type="NganhChinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NganhChinh" Member="NganhChinhs">
    <Type Name="NganhChinh">
      <Column Name="IdNganhChinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="NganhChinh_KhachHang" Member="KhachHangs" ThisKey="IdNganhChinh" OtherKey="NganhChinh" Type="KhachHang" />
      <Association Name="NganhChinh_Nganh" Member="Nganhs" ThisKey="IdNganhChinh" OtherKey="IdNganhChinh" Type="Nganh" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="IdNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhongBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="IdNhanVien" OtherKey="NhanVienLV" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.SoDuTinDung" Member="SoDuTinDungs">
    <Type Name="SoDuTinDung">
      <Column Name="IdTaiKhoan" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoDuTK" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayGiaTri" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDaoHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LaiSuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TaiKhoan_SoDuTinDung" Member="TaiKhoan" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="IdTaiKhoan" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienTe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TieuDeTK" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TieuDeNgan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NhanVienLV" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PhiMa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="Char(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdTaiKhoanLV" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="TaiKhoan_ChiTietGD" Member="ChiTietGDs" ThisKey="IdTaiKhoan" OtherKey="SoTKNguoiChuyen" Type="ChiTietGD" />
      <Association Name="TaiKhoan_ThamGiaTK" Member="ThamGiaTKs" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="ThamGiaTK" />
      <Association Name="TaiKhoan_GiaoDich" Member="GiaoDiches" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="GiaoDich" />
      <Association Name="TaiKhoan_SoDuTinDung" Member="SoDuTinDung" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoan" Type="SoDuTinDung" Cardinality="One" />
      <Association Name="TaiKhoan_TaiKhoan" Member="TaiKhoans" ThisKey="IdTaiKhoan" OtherKey="IdTaiKhoanLV" Type="TaiKhoan" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="LoaiTaiKhoan" ThisKey="IdLoai" OtherKey="IdLoai" Type="LoaiTaiKhoan" IsForeignKey="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="NhanVienLV" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="KhachHang_TaiKhoan" Member="KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="TaiKhoan_TaiKhoan" Member="TaiKhoan1" ThisKey="IdTaiKhoanLV" OtherKey="IdTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>